### ISSUE TITLE
npm is old

### ISSUE THREAD

**Issue by shinriyo** [imione/env-switcher#2]
npm package is old (last publish is "a year ago")

https://www.npmjs.com/package/env-switcher

I want to use `update` command, could you publish newest?

**Comment by imione** [comment]
I have not maintained this module since last year, so my apology
v1.1.0 will be deployed ASAP

**Comment by imione** [comment]
@shinriyo  I published v1.1.0, I hope that it will be helpful for ya

**Comment by shinriyo** [comment]
감사합니다
앞으로 잘 부탁합니다
